export const seedProducts = [
  // FURNITURE
  {
    name: 'Mid-Century Lounge Chair',
    slug: 'mid-century-lounge-chair',
    description: 'A beautifully crafted mid-century modern lounge chair with solid walnut legs and premium upholstery. Perfect for reading nooks and living rooms.',
    price: 89900,
    category: 'furniture',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80',
    ],
    dimensions: '32"W x 34"D x 33"H',
    material: 'Walnut wood, cotton blend fabric',
    inStock: true,
    featured: true,
  },
  {
    name: 'Minimalist Oak Coffee Table',
    slug: 'minimalist-oak-coffee-table',
    description: 'Clean lines and natural oak make this coffee table a versatile centerpiece for any living space.',
    price: 54900,
    category: 'furniture',
    images: [
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=800&q=80',
    ],
    dimensions: '48"W x 24"D x 18"H',
    material: 'Solid white oak',
    inStock: true,
    featured: true,
  },
  {
    name: 'Woven Rattan Accent Chair',
    slug: 'woven-rattan-accent-chair',
    description: 'Hand-woven natural rattan chair that brings warmth and texture to your living space.',
    price: 42900,
    category: 'furniture',
    images: [
      'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80',
    ],
    dimensions: '28"W x 30"D x 32"H',
    material: 'Natural rattan, steel frame',
    inStock: true,
    featured: false,
  },
  // LIGHTING
  {
    name: 'Brass Pendant Light',
    slug: 'brass-pendant-light',
    description: 'Elegant brass pendant light with a warm, diffused glow. Ideal for dining areas and entryways.',
    price: 22900,
    category: 'lighting',
    images: [
      'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&q=80',
    ],
    dimensions: '12" diameter x 14"H',
    material: 'Solid brass, frosted glass',
    inStock: true,
    featured: true,
  },
  {
    name: 'Ceramic Table Lamp',
    slug: 'ceramic-table-lamp',
    description: 'Handmade ceramic table lamp with linen shade. Each piece is uniquely textured.',
    price: 16900,
    category: 'lighting',
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80',
    ],
    dimensions: '8" diameter x 22"H',
    material: 'Ceramic, linen shade',
    inStock: true,
    featured: false,
  },
  {
    name: 'Modern Arc Floor Lamp',
    slug: 'modern-arc-floor-lamp',
    description: 'Statement arc floor lamp in matte black. Adjustable arm reaches over sofas and reading areas.',
    price: 34900,
    category: 'lighting',
    images: [
      'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800&q=80',
    ],
    dimensions: '15" base x 72"H, 40" reach',
    material: 'Powder-coated steel, marble base',
    inStock: true,
    featured: true,
  },
  // WALL ART
  {
    name: 'Abstract Canvas Triptych',
    slug: 'abstract-canvas-triptych',
    description: 'Three-piece abstract canvas set in warm earth tones. Ready to hang with included hardware.',
    price: 29900,
    category: 'wall-art',
    images: [
      'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80',
    ],
    dimensions: '3 panels, each 16"W x 24"H',
    material: 'Canvas, wooden frame',
    inStock: true,
    featured: true,
  },
  {
    name: 'Botanical Line Art Print',
    slug: 'botanical-line-art-print',
    description: 'Delicate botanical illustrations printed on museum-quality paper. Set of 3 prints.',
    price: 8900,
    category: 'wall-art',
    images: [
      'https://images.unsplash.com/photo-1582045253062-f63cfbd45bcb?w=800&q=80',
    ],
    dimensions: '11"W x 14"H each',
    material: 'Archival paper, 300gsm',
    inStock: true,
    featured: false,
  },
  {
    name: 'Macramé Wall Hanging',
    slug: 'macrame-wall-hanging',
    description: 'Handmade bohemian macramé wall hanging in natural cotton. Adds texture and warmth to any wall.',
    price: 12900,
    category: 'wall-art',
    images: [
      'https://images.unsplash.com/photo-1622372738946-62e02505feb3?w=800&q=80',
    ],
    dimensions: '24"W x 36"H',
    material: '100% natural cotton rope',
    inStock: true,
    featured: false,
  },
  // TEXTILES
  {
    name: 'Hand-Woven Throw Blanket',
    slug: 'hand-woven-throw-blanket',
    description: 'Luxuriously soft hand-woven throw in warm neutral tones. Perfect draped over a sofa or bed.',
    price: 13900,
    category: 'textiles',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    ],
    dimensions: '50"W x 60"L',
    material: 'Wool and cotton blend',
    inStock: true,
    featured: true,
  },
  {
    name: 'Linen Cushion Cover Set',
    slug: 'linen-cushion-cover-set',
    description: 'Set of 2 premium linen cushion covers with hidden zipper. Understated elegance for any sofa.',
    price: 5900,
    category: 'textiles',
    images: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80',
    ],
    dimensions: '18"W x 18"H',
    material: '100% European linen',
    inStock: true,
    featured: false,
  },
  {
    name: 'Moroccan Handwoven Rug',
    slug: 'moroccan-handwoven-rug',
    description: 'Authentic Moroccan area rug with geometric patterns. Each piece is one-of-a-kind.',
    price: 79900,
    category: 'textiles',
    images: [
      'https://images.unsplash.com/photo-1600166898405-da9535204843?w=800&q=80',
    ],
    dimensions: '5\'W x 8\'L',
    material: '100% wool',
    inStock: true,
    featured: true,
  },
  // ACCESSORIES
  {
    name: 'Artisan Ceramic Vase',
    slug: 'artisan-ceramic-vase',
    description: 'Handcrafted ceramic vase with organic curves and matte finish. A statement piece for any shelf.',
    price: 7900,
    category: 'accessories',
    images: [
      'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=800&q=80',
    ],
    dimensions: '6" diameter x 10"H',
    material: 'Hand-thrown ceramic',
    inStock: true,
    featured: false,
  },
  {
    name: 'Marble & Brass Bookends',
    slug: 'marble-brass-bookends',
    description: 'Pair of geometric bookends crafted from Carrara marble with brass inlay.',
    price: 6900,
    category: 'accessories',
    images: [
      'https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=800&q=80',
    ],
    dimensions: '5"W x 3"D x 7"H each',
    material: 'Carrara marble, solid brass',
    inStock: true,
    featured: false,
  },
  {
    name: 'Scented Soy Candle Trio',
    slug: 'scented-soy-candle-trio',
    description: 'Set of 3 hand-poured soy candles in amber glass jars. Scents: Cedar & Sage, Vanilla Bean, Bergamot.',
    price: 4500,
    category: 'accessories',
    images: [
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800&q=80',
    ],
    dimensions: '3" diameter x 4"H each',
    material: '100% soy wax, cotton wick',
    inStock: true,
    featured: true,
  },
  {
    name: 'Wooden Serving Tray',
    slug: 'wooden-serving-tray',
    description: 'Acacia wood serving tray with leather handles. Perfect for coffee tables and ottomans.',
    price: 5900,
    category: 'accessories',
    images: [
      'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80',
    ],
    dimensions: '18"W x 12"D x 3"H',
    material: 'Acacia wood, genuine leather',
    inStock: true,
    featured: false,
  },
  {
    name: 'Geometric Terrarium',
    slug: 'geometric-terrarium',
    description: 'Gold-framed glass terrarium for air plants and succulents. Adds a touch of green to any space.',
    price: 3900,
    category: 'accessories',
    images: [
      'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80',
    ],
    dimensions: '8"W x 8"D x 10"H',
    material: 'Glass panels, brass frame',
    inStock: true,
    featured: false,
  },
];
