version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      playwright:
        patterns:
          - "@playwright/*"
      next:
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/*"
      types:
        patterns:
          - "@types/*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
